Project-AllForOne/Back

src/main/java/com/banghyang/model/note/entity/BaseNote.java
src/main/java/com/banghyang/model/note/entity/MiddleNote.java
src/main/java/com/banghyang/model/note/entity/SingleNote.java
src/main/java/com/banghyang/model/note/entity/TopNote.java
src/main/java/com/banghyang/model/perfume/entity/Perfume.java
src/main/java/com/banghyang/model/perfume/entity/PerfumeImage.java
src/main/resources/data/perfume/perfume_image.json

향수 이미지 스키마 생성

---

src/main/java/com/banghyang/auth/common/config/WebConfig.java
src/main/java/com/banghyang/auth/kakao/client/KakaoAPIClient.java
src/main/java/com/banghyang/auth/kakao/config/KakaoHttpInterfaceConfig.java
src/main/java/com/banghyang/auth/kakao/config/KakaoOauthConfig.java
src/main/java/com/banghyang/auth/kakao/controller/KakaoController.java
src/main/java/com/banghyang/auth/kakao/model/dto/KakaoMemberResponse.java
src/main/java/com/banghyang/auth/kakao/model/dto/KakaoToken.java
src/main/java/com/banghyang/auth/kakao/model/dto/OauthId.java
src/main/java/com/banghyang/auth/kakao/model/dto/OauthMemberResponse.java
src/main/java/com/banghyang/auth/kakao/service/KakaoService.java
src/main/java/com/banghyang/auth/kakao/type/OauthServerType.java
src/main/java/com/banghyang/member/entity/Member.java
src/main/java/com/banghyang/member/repository/MemberRepository.java
src/main/java/com/banghyang/object/perfume/service/PerfumeService.java
src/main/java/com/banghyang/object/spice/dto/SpiceResponse.java
src/main/java/com/banghyang/object/spice/service/SpiceService.java

oauth 폴더명 변경해서 changes 많은 거니 긴장 푸세요
향수 향료 이름기준 정렬 했습니다 확인해보고 피드백 주세요

oauth 폴더명 변경, 향수 향료 리스트 이름 정렬

---

src/main/java/com/banghyang/object/spice/dto/SpiceResponse.java
src/main/java/com/banghyang/object/spice/entity/Spice.java
src/main/java/com/banghyang/object/spice/service/SpiceService.java

향수 영문, 한글명 함께 보내기

---

src/main/java/com/banghyang/auth/common/config/HttpInterfaceConfig.java
src/main/java/com/banghyang/object/note/entity/BaseNote.java
src/main/java/com/banghyang/object/note/entity/MiddleNote.java
src/main/java/com/banghyang/object/note/entity/SingleNote.java
src/main/java/com/banghyang/object/note/entity/TopNote.java
src/main/java/com/banghyang/object/perfume/controller/PerfumeController.java
src/main/java/com/banghyang/object/perfume/dto/MultiPerfumeResponse.java
src/main/java/com/banghyang/object/perfume/dto/PerfumeModifyRequest.java
src/main/java/com/banghyang/object/perfume/dto/SinglePerfumeResponse.java
src/main/java/com/banghyang/object/perfume/entity/Perfume.java
src/main/java/com/banghyang/object/perfume/entity/PerfumeImage.java
src/main/java/com/banghyang/object/perfume/service/PerfumeService.java
src/main/java/com/banghyang/object/spice/controller/SpiceController.java
src/main/java/com/banghyang/object/spice/dto/SpiceModifyRequest.java
src/main/java/com/banghyang/object/spice/dto/SpiceResponse.java
src/main/java/com/banghyang/object/spice/entity/Spice.java
src/main/java/com/banghyang/object/spice/entity/SpiceImage.java
src/main/java/com/banghyang/object/spice/repository/SpiceRepository.java
src/main/java/com/banghyang/object/spice/service/SpiceService.java
src/main/resources/data/spice/spice.json

향료향수 수정, 삭제 기능

---

src/main/java/com/banghyang/recommend/config/RestTemplateConfig.java
src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/service/ImageGenerationService.java
src/main/java/com/banghyang/recommend/service/ImageProcessingService.java
src/main/java/com/banghyang/recommend/service/LLMService.java
src/main/java/com/banghyang/recommend/service/RecommendService.java

- fastapi 로 python 연결
- RecommendController
- 향수 추천 전반을 관리
- RecommendService
- LLMService ,  ImageProcessingService,ImageGenerationService 관리

[FEAT] Fastapi 연동

---

src/main/java/com/banghyang/object/line/repository/LineRepository.java
src/main/java/com/banghyang/object/perfume/controller/PerfumeController.java
src/main/java/com/banghyang/object/perfume/dto/PerfumeCreateRequest.java
src/main/java/com/banghyang/object/perfume/service/PerfumeService.java
src/main/java/com/banghyang/object/spice/controller/SpiceController.java
src/main/java/com/banghyang/object/spice/dto/SpiceCreateRequest.java
src/main/java/com/banghyang/object/spice/entity/Spice.java
src/main/java/com/banghyang/object/spice/service/SpiceService.java

향수, 향료 신규 등록 기능

---

src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/service/ImageGenerationService.java
src/main/java/com/banghyang/recommend/service/ImageProcessingService.java
src/main/java/com/banghyang/recommend/service/RecommendService.java

- python 에서 오는 prompt 수정중
- image 생성 문제 해결

[FIX] Back router

---

src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/service/RecommendService.java

- MultipartFile 처리 추가
service 에서만 multipartfile 의 내용을 판별하도록 했는데 controlloer 에서도 관리하도록 수정

[FIX] recommend post

---

src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/service/RecommendService.java

[FIX] recommend service put

---

build.gradle
src/main/java/com/banghyang/recommend/config/AwsS3Config.java
src/main/java/com/banghyang/recommend/entity/ChatImage.java
src/main/java/com/banghyang/recommend/repository/ChatImageRepository.java
src/main/java/com/banghyang/recommend/service/ImageGenerationService.java
src/main/java/com/banghyang/recommend/service/ImageProcessingService.java
src/main/java/com/banghyang/recommend/service/S3Service.java

- chatImage 추가
- ChatImageRepository 추가
- imagegenerationservice s3 올리기 수정
- imageproccessingservice s3 올리기 수정

s3에 이미지 올리기

---

src/main/java/com/banghyang/object/mapper/Mapper.java
src/main/java/com/banghyang/object/perfume/dto/PerfumeResponse.java

매퍼에서 entity를 참조하지않고 response를 참조하고있어서 정보가 누락되었었네요
브랜드와 부향률 정보도 추가 했습니다.

향수 조회 정보 누락 수정

---

src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/service/ImageProcessingService.java

 Image넣었을때 향수 추천하게 수정

---

src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/service/RecommendService.java

recommend 수정

---

src/main/java/com/banghyang/recommend/service/RecommendService.java

api 응답 데이터에 이미지 url 추가

---

src/main/java/com/banghyang/auth/kakao/controller/KakaoController.java
src/main/java/com/banghyang/auth/kakao/model/dto/OauthMemberResponse.java
src/main/java/com/banghyang/member/service/MemberService.java
src/main/java/com/banghyang/object/mapper/Mapper.java

멤버 로그인 시 로그인 유저 정보 중 id 추가

---

src/main/java/com/banghyang/object/spice/dto/SpiceResponse.java

향료 response의 line을 lineName으로 수정

---

src/main/java/com/banghyang/object/mapper/Mapper.java

향료 mapper의 속성이름 변경으로 mapper도 수정

---

build.gradle
src/main/java/com/banghyang/recommend/config/MongoConfig.java
src/main/java/com/banghyang/recommend/controller/RecommendController.java
src/main/java/com/banghyang/recommend/dto/ChatDto.java
src/main/java/com/banghyang/recommend/dto/ChatImageDto.java
src/main/java/com/banghyang/recommend/entity/Chat.java
src/main/java/com/banghyang/recommend/entity/ChatImage.java
src/main/java/com/banghyang/recommend/repository/ChatImageRepository.java
src/main/java/com/banghyang/recommend/repository/ChatRepository.java
src/main/java/com/banghyang/recommend/service/RecommendService.java

connecting to mongo db

---

src/main/java/com/banghyang/chat/controller/chatController.java
src/main/java/com/banghyang/chat/dto/ChatResponse.java
src/main/java/com/banghyang/chat/dto/UserResponse.java
src/main/java/com/banghyang/chat/entity/Chat.java
src/main/java/com/banghyang/chat/service/ChatService.java
src/main/java/com/banghyang/common/mapper/Mapper.java
src/main/java/com/banghyang/member/service/MemberService.java
src/main/java/com/banghyang/object/perfume/service/PerfumeService.java
src/main/java/com/banghyang/object/spice/service/SpiceService.java

채팅 기록 조회 기능

---

src/main/java/com/banghyang/chat/dto/ChatResponse.java
src/main/java/com/banghyang/chat/service/ChatService.java
src/main/java/com/banghyang/chat/service/S3Service.java
src/main/java/com/banghyang/common/util/ValidUtils.java

AI 채팅기능 최종 연결 완료

---

src/main/java/com/banghyang/chat/dto/UserResponse.java
src/main/java/com/banghyang/chat/service/ChatService.java

누락 되었던 memberId와 timeStamp 추가했습니다

최종 유저 response 필드값 누락항목 추가

---

src/main/java/com/banghyang/chat/entity/Chat.java
src/main/java/com/banghyang/common/config/MongoConfig.java

채팅 타임스탬프 누락 수정

---

src/main/java/com/banghyang/chat/dto/UserResponse.java
src/main/java/com/banghyang/chat/service/ChatService.java

채팅 타입 누락 추가

---

src/main/java/com/banghyang/history/controller/HistoryController.java

history controller url 수정

---

src/main/java/com/banghyang/common/type/MemberRoleType.java
src/main/java/com/banghyang/member/controller/MemberController.java
src/main/java/com/banghyang/member/entity/Member.java
src/main/java/com/banghyang/member/service/MemberService.java

RoleType에 Leave 상태를 추가하여 탈퇴상태 처리 가능하게 하였습니더다.
컨트롤러에 탈퇴 처리 엔드포인트 추가하였습니다.
서비스 클래스에 탈퇴 처리 메소드 추가하였습니다.
멤버 엔티티에 탈퇴 상태로 변경 + 탈퇴시 시간 찍히게 해뒀습니다.

멤버 탈퇴처리 기능 추가

---

src/main/java/com/banghyang/history/entity/History.java
src/main/java/com/banghyang/history/entity/Recommendations.java
src/main/java/com/banghyang/history/service/HistoryService.java

불필요했던 타입, 모드, 이미지 URL 필드 제거했습니다

히스토리 불필요한 필드값 제거

---

src/main/java/com/banghyang/member/controller/MemberController.java
src/main/java/com/banghyang/member/service/MemberService.java

POST로 잘못되어있던거 PUT으로 변경했습니다.
@RequestPram도 @PathVariable로 잘 변경했습니다

회원 탈퇴 메소드 PUT으로 변경

---

src/main/java/com/banghyang/chat/service/ChatService.java

서비스 클래스에서 userRequest에서 값 가져오던것
perfumeRecommendResponse에서 값 가져오게 수정했습니다

일반 모드 답변 엔티티 저장시 content 잘못 담긴 것 수정

---

build.gradle
src/main/java/com/banghyang/common/config/CacheConfig.java
src/main/java/com/banghyang/object/perfume/controller/PerfumeController.java
src/main/java/com/banghyang/object/perfume/service/PerfumeService.java

향수 조회 페이지 접속시마다 로딩이 너무 오래 걸려서 캐싱 추가했습니다
추후엔 페이징과 캐싱을 같이 사용하고, 필터 및 검색 기능도 백에서 처리하는것으로 개선 예정
* 캐싱 의존성 추가
* 캐싱 config 클래스 추가
* perfume service 클래스 메소드 단위에 캐싱 관련 어노테이션 추가

향수 조회 페이지 캐싱 사용

---

src/main/java/com/banghyang/history/controller/HistoryController.java
src/main/java/com/banghyang/history/dto/HistoryResponse.java
src/main/java/com/banghyang/history/entity/History.java
src/main/java/com/banghyang/history/entity/Recommendation.java
src/main/java/com/banghyang/history/repository/HistoryRepository.java
src/main/java/com/banghyang/history/repository/RecommendationRepository.java
src/main/java/com/banghyang/history/service/HistoryService.java
src/main/java/com/banghyang/member/entity/Member.java

멤버 - 히스토리 양방향
히스토리 - 추천 양방향 설정
히스토리 서비스 클래스 코드 수정

히스토리 기능 및 연관관계 수정

---

src/main/java/com/banghyang/chat/repository/ChatRepository.java
src/main/java/com/banghyang/history/controller/HistoryController.java
src/main/java/com/banghyang/history/service/HistoryService.java

히스토리 생성시 채팅 조회하는 기준을 imageUrl로 변경하였습니다.
history controller 변경
history service 변경
chat repository에서 imageUrl로 채팅 기록 찾는 메소드 추가

히스토리 생성시 채팅 조회 기준 imageUrl로 변경

---

src/main/java/com/banghyang/object/product/controller/ProductController.java
src/main/java/com/banghyang/object/product/dto/DiffuserResponse.java
src/main/java/com/banghyang/object/product/dto/UserRequest.java
src/main/java/com/banghyang/object/product/dto/UserResponse.java
src/main/java/com/banghyang/object/product/service/ProductService.java

- ai server와 연결 성공
- response에 recommendation과 usage_routine 포함 image_url까지 포함하여 클라이언트에게 보낼 수 있도록 했음

[FEAT] Fragrance therapy recommendation( 향 테라피(웰니스) 서비스 ) 

---

src/main/java/com/banghyang/chat/controller/chatController.java
src/main/java/com/banghyang/chat/dto/UserChatRequest.java
src/main/java/com/banghyang/chat/dto/UserChatResponse.java
src/main/java/com/banghyang/chat/service/ChatService.java
src/main/java/com/banghyang/diffuser/controller/DiffuserKeywordController.java
src/main/java/com/banghyang/diffuser/dto/DiffuserKeywordRequest.java
src/main/java/com/banghyang/diffuser/dto/DiffuserKeywordResponse.java
src/main/java/com/banghyang/diffuser/dto/DiffuserResponse.java
src/main/java/com/banghyang/diffuser/service/DiffuserKeywordService.java
src/main/java/com/banghyang/object/product/controller/ProductController.java
src/main/java/com/banghyang/object/product/service/ProductService.java

키워드 기반 디퓨저 추천 기능 관련 내용들을 diffuser 폴더에 분리하였습니다.

키워드 기반 디퓨저 추천 패키지 분리

---

src/main/java/com/banghyang/diffuser/dto/DiffuserKeywordResponse.java
src/main/java/com/banghyang/diffuser/dto/DiffuserResponse.java
src/main/java/com/banghyang/diffuser/service/DiffuserKeywordService.java

[[FIX] 테라피기반 디퓨저 추천 수정

---

src/main/java/com/banghyang/object/product/controller/ProductController.java
src/main/java/com/banghyang/object/product/dto/ProductDetailResponse.java
src/main/java/com/banghyang/object/product/dto/SimilarPerfumeResponse.java
src/main/java/com/banghyang/object/product/entity/ProductImage.java
src/main/java/com/banghyang/object/product/service/ProductService.java
src/main/java/com/banghyang/object/product/service/SimilarPerfumeService.java
src/main/java/com/banghyang/object/review/controller/ReviewController.java
src/main/java/com/banghyang/object/review/dto/ReviewResponse.java
src/main/java/com/banghyang/object/review/repository/ReviewRepository.java
src/main/java/com/banghyang/object/review/service/ReviewService.java

- AI-Server에 유사 향수 추천 연동
- 특정 향수에 대한 리뷰 조회 기능 구현

향수 상세 조회 기능 구현

---

src/main/java/com/banghyang/object/product/controller/ProductController.java
src/main/java/com/banghyang/object/product/dto/ProductDetailResponse.java
src/main/java/com/banghyang/object/product/service/ProductService.java
src/main/java/com/banghyang/object/product/service/SimilarPerfumeService.java
src/main/java/com/banghyang/object/review/controller/ReviewController.java
src/main/java/com/banghyang/object/review/service/ReviewService.java

- 리뷰와 유사향수 서비스 캐싱처리
- ProductDetailResponse에서 review 제외
- ProductController에 리뷰요약 api 삭제

FIX] 향수 상세페이지 수정

---

src/main/java/com/banghyang/object/review/controller/ReviewController.java
src/main/java/com/banghyang/object/review/dto/MyReviewResponse.java
src/main/java/com/banghyang/object/review/repository/ReviewRepository.java
src/main/java/com/banghyang/object/review/service/ReviewService.java

[FEAT] 내가 작성한 리뷰 조회

---

src/main/java/com/banghyang/object/bookmark/controller/BookmarkController.java
src/main/java/com/banghyang/object/bookmark/dto/BookmarkedPerfumeResponse.java
src/main/java/com/banghyang/object/bookmark/repository/BookmarkRepository.java
src/main/java/com/banghyang/object/bookmark/service/BookmarkService.java
src/main/java/com/banghyang/object/product/service/ProductService.java

- AI 북마크 유사 향수 추천과 연동
- 북마크 토클 생성 및 삭제 구현
- 북마크 조회, 삭제 구현

북마크 기능 구현 Feature/bookmark create

---

src/main/java/com/banghyang/object/heart/controller/HeartController.java
src/main/java/com/banghyang/object/heart/dto/HeartRequest.java
src/main/java/com/banghyang/object/heart/entity/Heart.java
src/main/java/com/banghyang/object/heart/repository/HeartRepository.java
src/main/java/com/banghyang/object/heart/service/HeartService.java
src/main/java/com/banghyang/object/like/controller/HeartController.java
src/main/java/com/banghyang/object/like/dto/HeartRequest.java
src/main/java/com/banghyang/object/like/repository/HeartRepository.java
src/main/java/com/banghyang/object/like/service/HeartService.java
src/main/java/com/banghyang/object/review/controller/ReviewController.java
src/main/java/com/banghyang/object/review/dto/ReviewResponse.java
src/main/java/com/banghyang/object/review/service/ReviewService.java

HeartController (컨트롤러)
DELETE /likes/{reviewId} 요청을 받아 서비스 계층에 전달.
reviewId가 null이면 400 Bad Request 반환.
삭제 성공 여부에 따라 200 OK 또는 400 Bad Request 응답.
HeartService (서비스)
deleteByReviewId(reviewId) 실행 후 삭제된 행 수를 확인.
삭제된 데이터가 없으면 로그 출력 후 false 반환.
HeartRepository
reviewId 기준으로 좋아요 데이터 삭제.

[FEAT] Add_Delete_likes

---

src/main/java/com/banghyang/object/product/entity/ProductImage.java
src/main/java/com/banghyang/object/product/service/ProductService.java
src/main/java/com/banghyang/object/review/dto/MyReviewResponse.java
src/main/java/com/banghyang/object/review/service/ReviewService.java

제품 조회시 배경제거를 한 버젼의 이미지를 먼저 가져오고 없을시 기존 버전을 들고오도록 수정

제품 조회 시 배경제거 이미지를 우선 가져오도록 수정

---

src/main/java/com/banghyang/scentlens/controller/ScentlensController.java
src/main/java/com/banghyang/scentlens/dto/ProductResponse.java
src/main/java/com/banghyang/scentlens/dto/WrappedProductResponse.java
src/main/java/com/banghyang/scentlens/service/ScentlensService.java

- 센트렌즈 AI 서버에서 검색된 product 리스트 응답 받아와서 리턴

[FEAT] 센트렌즈 AI 서버에서 응답 받아오는 기능 추가

---

src/main/java/com/banghyang/object/review/service/ReviewService.java

- 리뷰 캐시때문에 좋아요 카운팅이 반영이 안돼서 캐시를 적용을 지움

[FIX] 특정 향수 리뷰 좋아요 카운팅 수정

---

src/main/java/com/banghyang/object/review/service/ReviewService.java

리뷰 요약 살짝 수정

---

src/main/java/com/banghyang/chat/service/ChatService.java

- 이미지 요청 에러 핸들링 (Stable Diffusion 과부하로 오류 발생하면 채팅 답변도 받아오지 않는 오류 핸들)
- 채팅 답변이 생성되었음에도 이미지 반환이 안되면 url을 null로 처리
- AI 서버에서 이미지를 보내도 상황에 따라 일반 대화로 라우팅될 수 있게 수정하여 백에서도 이미지가 있으면 일반 대화 모드로부터 무조건 자동 제외되는 부분 수정

[FIX] 이미지 요청 에러 핸들링, 채팅에 이미지만 요청하거나 텍스트만 존재하더라도 오류없이 처리 가능하도록 수정

---

src/main/java/com/banghyang/object/product/dto/PerfumeResponse.java
src/main/java/com/banghyang/object/product/entity/Product.java
src/main/java/com/banghyang/object/product/service/ProductService.java

- product entity에 price 추가
- PerfumeResponse에 price 추가
- ProductService에 getAllProductResponses에 price 추가
- 안쓰이는 import 삭제
- 내용이 안쓰여있는 주석에 내용 채우기

[FEAT] product에 price 추가

---

src/main/java/com/banghyang/object/product/controller/ProductController.java
src/main/java/com/banghyang/object/product/dto/ProductDetailSimilarResponse.java
src/main/java/com/banghyang/object/product/service/ProductService.java

- ProductService 향수 전체 조회 부분에서 노트조회 코드 간결하게 수정
- ProductDetailResponse클래스 이름 ProductDetailSimilarResponse으로 변경
- 주석 수정

product 관련 부분 코드 수정
